---

- name: Preflight checks - network
  ansible.builtin.assert:
    that:
      - vaultwarden_container_network_name != ''
    quiet: true
  when:
    - vaultwarden_container_exposed_port == ''


- name: Preflight checks
  ansible.builtin.assert:
    that:
      - vaultwarden_container_admin_token != ''
      - vaultwarden_container_base_dir != ''
      - vaultwarden_container_data_dir != ''
      - vaultwarden_container_name != ''
      - vaultwarden_container_network_name != ''
      - vaultwarden_container_restart_policy != ''
      - vaultwarden_container_url != ''
      - vaultwarden_container_version != ''
    quiet: true

